name: Main Build and Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Call the reusable build workflow
    uses: ./.github/workflows/templates/build-template.yml
    with:
      java-version: '17'
      build-command: 'mvn clean install && mvn clean package'

  sonar:
    # Call the reusable SonarQube workflow
    needs: build  # Ensure the build job completes first
    uses: ./.github/workflows/templates/sonar-template.yml

  push_to_artifactory:
    # Call the reusable push-to-artifactory workflow
    needs: [build, sonar]  # Ensure build and sonar jobs complete first
    uses: ./.github/workflows/templates/push-template.yml
    with:
      jfrog-url: ${{ secrets.JFROG_URL }}
      jfrog-user: ${{ secrets.JFROG_USER }}
      jfrog-apikey: ${{ secrets.JFROG_API_KEY }}

  deploy:
    # Call the reusable deploy workflow
    needs: push_to_artifactory  # Ensure push_to_artifactory job completes first
    uses: ./.github/workflows/templates/deploy-template.yml
    with:
      EC2_IP: ${{ secrets.EC2_PUBLIC_DNS }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      EC2_SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
