name: Main Build and Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: engrhamza14/Java-App/.github/workflows/build-template.yml@main
    

  sonar:
    needs: build  # Ensure the Build job completes first
    uses: engrhamza14/Java-App/.github/workflows/sonar-template.yml@main
    secrets:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  push_to_artifactory:
    needs: [build, sonar]  # Ensure Build and SonarQube jobs complete first
    uses: engrhamza14/Java-App/.github/workflows/push-template.yml@main
    secrets:
      JFROG_USER: ${{ secrets.JFROG_USER}}  # Needed to get PR information, if any
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

  deploy:
    needs: push_to_artifactory  # Ensure the Push to Artifactory job completes first
    uses: engrhamza14/Java-App/.github/workflows/deploy-template.yml@main
    secrets:
      JFROG_USER: ${{ secrets.JFROG_USER}}  # Needed to get PR information, if any
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEYL }}
      EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}

