name: Main Build and Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Application
    uses: engrhamza14/Java-App/.github/workflows/build.yml@main
    with:
      java-version: '17'
      build-command: 'mvn clean install && mvn clean package'

  sonar:
    name: Run SonarQube Analysis
    needs: build  # Ensure the Build job completes first
    uses: engrhamza14/Java-App/.github/workflows/sonar-template.yml@main

  push_to_artifactory:
    name: Push Artifact to Artifactory
    needs: [build, sonar]  # Ensure Build and SonarQube jobs complete first
    uses: engrhamza14/Java-App/.github/workflows/push-template.yml@main
    with:
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}

  deploy:
    name: Deploy to EC2
    needs: push_to_artifactory  # Ensure the Push to Artifactory job completes first
    uses: engrhamza14/Java-App/.github/workflows/deploy-template.yml@main
    with:
      EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
