name: Main Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: engrhamza14/Java-App/.github/workflows/build-template.yml@main

  sonar:
    needs: build
    uses: engrhamza14/Java-App/.github/workflows/sonar-template.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  push_to_artifactory:
    needs: [build, sonar]
    uses: engrhamza14/Java-App/.github/workflows/push-template.yml@main
    secrets:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
