name: Main Build and Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: engrhamza14/Java-App/.github/workflows/build-template.yml@main

  sonar:
    needs: build  # Ensure the Build job completes first
    uses: engrhamza14/Java-App/.github/workflows/sonar-template.yml@main

  push_to_artifactory:
    needs: [build, sonar]  # Ensure Build and SonarQube jobs complete first
    uses: engrhamza14/Java-App/.github/workflows/push-template.yml@main

  deploy:
    needs: push_to_artifactory  # Ensure the Push to Artifactory job completes first
    uses: engrhamza14/Java-App/.github/workflows/deploy-template.yml@main
