name: Main Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: engrhamza14/Java-App/.github/workflows/build-template.yml@main

  sonar:
    needs: build
    uses: engrhamza14/Java-App/.github/workflows/sonar-template.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  push_to_artifactory:
    needs: [build, sonar]
    uses: engrhamza14/Java-App/.github/workflows/push-template.yml@main
    secrets:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

  confirm_deploy:
    name: Confirm Deployment
    runs-on: ubuntu-latest
    needs: push_to_artifactory
    steps:
      - name: Ask for Confirmation
        id: confirm
        run: |
          echo "::set-output name=deploy_confirmation::$(read -p 'Do you want to deploy? (yes/no): ' choice && echo $choice)"
      - name: Stop if No
        if: steps.confirm.outputs.deploy_confirmation != 'yes'
        run: |
          echo "Deployment not triggered as user chose 'no'."
          exit 0
      - name: Trigger Deploy Workflow
        if: steps.confirm.outputs.deploy_confirmation == 'yes'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Main Deploy Workflow
          token: ${{ secrets.GITHUB_TOKEN }}
