name: Deploy to EC2 and Run Spring Boot Project
on:
  workflow_call:
    secrets:
      EC2_PUBLIC_DNS:
        required: true
      EC2_PRIVATE_KEY:
        required: true
      JFROG_URL:
        required: true
      JFROG_USER:
        required: true
      JFROG_API_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secrets
        run: |
          echo "EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}"
          echo "JFROG_URL: ${{ secrets.JFROG_URL }}"
          echo "JFROG_USER: ${{ secrets.JFROG_USER }}"
        shell: bash

      - name: SSH into EC2 and configure JFrog CLI
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # Install JFrog CLI on EC2
            curl -fL https://getcli.jfrog.io | sh
            sudo mv jfrog /usr/local/bin
            # Configure JFrog CLI with your Artifactory credentials
            jfrog config add my-server \
              --artifactory-url=${{ secrets.JFROG_URL }} \
              --user=${{ secrets.JFROG_USER }} \
              --apikey=${{ secrets.JFROG_API_KEY }} \
              --interactive=false \
              --overwrite=true
            # Download the artifact directly on EC2
            jfrog rt download "artifactory-repo/libs-release-local/*.jar" /home/ubuntu/
            # Run the Spring Boot application in the background
            nohup java -jar /home/ubuntu/libs-release-local/springboot-test-0.0.1-SNAPSHOT.jar & 
            



