name: Main Deploy Workflow

on:
  workflow_dispatch: # Allows manual triggering of the deploy workflow

jobs:
  deploy:
    uses: engrhamza14/Java-App/.github/workflows/deploy-template.yml@main
    secrets:
      JFROG_USER: ${{ secrets.JFROG_USER }}
      JFROG_URL: ${{ secrets.JFROG_URL }}
      JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}


      