name: Build and Deploy to Artifactory
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin
      - name: Configure JFrog CLI
        run: |
          jfrog config add my-server \
            --artifactory-url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USER }} \
            --apikey=${{ secrets.JFROG-APIKEY }} \
            --interactive=false
      - name: Verify JFrog CLI Configuration
        run: |
          jfrog config show
      - name: Build Project
        run: |
          mvn clean install && mvn clean package
      - name: Upload Artifacts to Artifactory
        run: |
          jfrog rt upload "target/*.jar" artifactory-repo/libs-release-local/ --url=${{ secrets.JFROG_URL }} --user=${{ secrets.JFROG_USER }} --password=your-password
